# Exercícios da Aula 1

1 - Leia os dados com erro novamente, faça a limpeza e remova as duas últimas colunas.

In [16]:
import pandas as pd

data = pd.read_csv("/home/edmurcn/Documentos/MeusProjetos/Fis._Estat._Comp./Intro._Ciencia_Dados/data/iris-with-errors.csv", header=0)
data.head(25)

sepal_length sepal_width  petal_length petal_width    species
0           5.1         3.5           1.4         0.2  duplicada
1           5.1         3.5           1.4         0.2  duplicada
2             ?           3           1.4         0.2     setosa
3           4.7         3.2           1.3         0.2     setosa
4           5.1         3.5           1.4         0.2  duplicada
5           NaN         3.1           1.5         0.2     setosa
6             5         3.6           1.4         0.2     setosa
7           5.4         3.9           1.7         0.4  duplicada
8           5.4         3.9           1.7         0.4  duplicada
9           4.6         3.4           1.4         NaN     setosa
10            5         3.4           1.5         0.2     setosa
11          4.4         2.9           1.4         0.2  duplicada
12          4.9         3.1           1.5         0.1     setosa
13          5.4         3.7           1.5         0.2     setosa
14          4.4         2.9           1.4         0.2  duplicada
15          4.8         3.4           1.6         0.2     setosa
16          4.8           3           1.4         0.1     setosa
17          4.4         2.9           1.4         0.2  duplicada
18          4.3           3           1.1         0.1     setosa
19          5.8           4           1.2         0.2     setosa
20          5.7         4.4           1.5         0.4     setosa
21          5.4         3.9           1.3           ?     setosa
22          5.1         3.5           1.4         0.3     setosa
23          5.7           ?           1.7         0.3     setosa
24          NaN         3.8           1.5         0.3     setosa

In [17]:
import numpy as np

data = data.replace("?", np.nan)
data.head(25)

sepal_length sepal_width  petal_length petal_width    species
0           5.1         3.5           1.4         0.2  duplicada
1           5.1         3.5           1.4         0.2  duplicada
2           NaN           3           1.4         0.2     setosa
3           4.7         3.2           1.3         0.2     setosa
4           5.1         3.5           1.4         0.2  duplicada
5           NaN         3.1           1.5         0.2     setosa
6             5         3.6           1.4         0.2     setosa
7           5.4         3.9           1.7         0.4  duplicada
8           5.4         3.9           1.7         0.4  duplicada
9           4.6         3.4           1.4         NaN     setosa
10            5         3.4           1.5         0.2     setosa
11          4.4         2.9           1.4         0.2  duplicada
12          4.9         3.1           1.5         0.1     setosa
13          5.4         3.7           1.5         0.2     setosa
14          4.4         2.9           1.4         0.2  duplicada
15          4.8         3.4           1.6         0.2     setosa
16          4.8           3           1.4         0.1     setosa
17          4.4         2.9           1.4         0.2  duplicada
18          4.3           3           1.1         0.1     setosa
19          5.8           4           1.2         0.2     setosa
20          5.7         4.4           1.5         0.4     setosa
21          5.4         3.9           1.3         NaN     setosa
22          5.1         3.5           1.4         0.3     setosa
23          5.7         NaN           1.7         0.3     setosa
24          NaN         3.8           1.5         0.3     setosa

In [18]:
data = data.dropna()
data.head(25)

sepal_length sepal_width  petal_length petal_width    species
0           5.1         3.5           1.4         0.2  duplicada
1           5.1         3.5           1.4         0.2  duplicada
3           4.7         3.2           1.3         0.2     setosa
4           5.1         3.5           1.4         0.2  duplicada
6             5         3.6           1.4         0.2     setosa
7           5.4         3.9           1.7         0.4  duplicada
8           5.4         3.9           1.7         0.4  duplicada
10            5         3.4           1.5         0.2     setosa
11          4.4         2.9           1.4         0.2  duplicada
12          4.9         3.1           1.5         0.1     setosa
13          5.4         3.7           1.5         0.2     setosa
14          4.4         2.9           1.4         0.2  duplicada
15          4.8         3.4           1.6         0.2     setosa
16          4.8           3           1.4         0.1     setosa
17          4.4         2.9           1.4         0.2  duplicada
18          4.3           3           1.1         0.1     setosa
19          5.8           4           1.2         0.2     setosa
20          5.7         4.4           1.5         0.4     setosa
22          5.1         3.5           1.4         0.3     setosa

In [20]:
data = data.drop_duplicates()
print("Colunas excluídas:", data.columns[[3,4]])
data = data.drop(data.columns[[3,4]], axis=1)
data.head(25)

Colunas excluídas: Index(['petal_width', 'species'], dtype='object')


sepal_length sepal_width  petal_length
0           5.1         3.5           1.4
3           4.7         3.2           1.3
6             5         3.6           1.4
7           5.4         3.9           1.7
10            5         3.4           1.5
11          4.4         2.9           1.4
12          4.9         3.1           1.5
13          5.4         3.7           1.5
15          4.8         3.4           1.6
16          4.8           3           1.4
18          4.3           3           1.1
19          5.8           4           1.2
20          5.7         4.4           1.5
22          5.1         3.5           1.4

2 - Leia os dados com erro novamente e insira a mediana de cada atributo onde for encontrada NaN.

In [24]:
data = pd.read_csv("/home/edmurcn/Documentos/MeusProjetos/Fis._Estat._Comp./Intro._Ciencia_Dados/data/iris-with-errors.csv", header=0)
data = data.replace('?', np.nan)

In [36]:
X = np.array(data[data.columns[0:data.shape[1]-1]], dtype=float)

median = np.nanmedian(X, axis=0) #cálculo da mediana de cada coluna

for i in np.arange(0, X.shape[0]):
    for j in np.arange(0, X.shape[1]):
        if (np.isnan(X[i,j]) == True):
            X[i,j] = median[j]

print(X)

[[5.1  3.5  1.4  0.2 ]
 [5.1  3.5  1.4  0.2 ]
 [5.05 3.   1.4  0.2 ]
 [4.7  3.2  1.3  0.2 ]
 [5.1  3.5  1.4  0.2 ]
 [5.05 3.1  1.5  0.2 ]
 [5.   3.6  1.4  0.2 ]
 [5.4  3.9  1.7  0.4 ]
 [5.4  3.9  1.7  0.4 ]
 [4.6  3.4  1.4  0.2 ]
 [5.   3.4  1.5  0.2 ]
 [4.4  2.9  1.4  0.2 ]
 [4.9  3.1  1.5  0.1 ]
 [5.4  3.7  1.5  0.2 ]
 [4.4  2.9  1.4  0.2 ]
 [4.8  3.4  1.6  0.2 ]
 [4.8  3.   1.4  0.1 ]
 [4.4  2.9  1.4  0.2 ]
 [4.3  3.   1.1  0.1 ]
 [5.8  4.   1.2  0.2 ]
 [5.7  4.4  1.5  0.4 ]
 [5.4  3.9  1.3  0.2 ]
 [5.1  3.5  1.4  0.3 ]
 [5.7  3.45 1.7  0.3 ]
 [5.05 3.8  1.5  0.3 ]]


3 - Conside os dados da Iris e mostre a distribuição de probabilidades de cada uma das variáveis após a normalização e padronização.

In [38]:
data = pd.read_csv("/home/edmurcn/Documentos/MeusProjetos/Fis._Estat._Comp./Intro._Ciencia_Dados/data/iris.csv", header=0)
data.head(10)

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa

In [40]:
from sklearn.preprocessing import MinMaxScaler

X = np.array(data[data.columns[0:data.shape[1]-1]], dtype=float)

scaler = MinMaxScaler(feature_range = (0,1)) #Função da normalização

X_norm = scaler.fit_transform(X)

print(X_norm)

[[0.22222222 0.625      0.06779661 0.04166667]
 [0.16666667 0.41666667 0.06779661 0.04166667]
 [0.11111111 0.5        0.05084746 0.04166667]
 [0.08333333 0.45833333 0.08474576 0.04166667]
 [0.19444444 0.66666667 0.06779661 0.04166667]
 [0.30555556 0.79166667 0.11864407 0.125     ]
 [0.08333333 0.58333333 0.06779661 0.08333333]
 [0.19444444 0.58333333 0.08474576 0.04166667]
 [0.02777778 0.375      0.06779661 0.04166667]
 [0.16666667 0.45833333 0.08474576 0.        ]
 [0.30555556 0.70833333 0.08474576 0.04166667]
 [0.13888889 0.58333333 0.10169492 0.04166667]
 [0.13888889 0.41666667 0.06779661 0.        ]
 [0.         0.41666667 0.01694915 0.        ]
 [0.41666667 0.83333333 0.03389831 0.04166667]
 [0.38888889 1.         0.08474576 0.125     ]
 [0.30555556 0.79166667 0.05084746 0.125     ]
 [0.22222222 0.625      0.06779661 0.08333333]
 [0.38888889 0.75       0.11864407 0.08333333]
 [0.22222222 0.75       0.08474576 0.08333333]
 [0.30555556 0.58333333 0.11864407 0.04166667]
 [0.22222222 